name: Build & Deploy MyMoviesApp


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Setup .NET (change the version if needed)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3) Setup Node so we can build Angular
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 4) Install & Build Angular in the "MyApp" folder
      - name: Build Angular
        run: |
          cd MyApp
          npm install
          npm run build -- --configuration production

      # 5) dotnet restore
      - name: Restore .NET
        run: dotnet restore MyMoviesApp.sln

      # 6) dotnet build
      - name: Build .NET
        run: dotnet build MyMoviesApp.sln --configuration Release --no-restore

      # 7) dotnet publish (specifically the API project)
      - name: Publish .NET API
        run: dotnet publish ./MyMoviesApp.Api/MyMoviesApp.Api.csproj -c Release -o out

      # 8) Azure login action - this is crucial so the deploy action has credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 9) Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "YOUR-WEBAPP-NAME"
          slot-name: "Production"
          package: "./MyMoviesApp.Api/out"
