name: Build and Deploy .NET + Angular

on:
  push:
    branches:
      - main
  # Allows manual runs from GitHub's "Actions" tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1) Check out
      - name: "Check out code"
        uses: actions/checkout@v3

      # 2) Set up .NET
      - name: "Set up .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"  # or "6.0.x" / "8.0.x" etc.
          
      # 3) Set up Node
      - name: "Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      # 4) Build Angular
      - name: "Install Angular deps"
        run: npm install
        working-directory: MyApp
        
      - name: "Build Angular"
        run: npm run build
        working-directory: MyApp

      # 5) Build .NET
      - name: "Restore .NET"
        run: dotnet restore MyMoviesApp.sln

      - name: "Build .NET"
        run: dotnet build MyMoviesApp.sln --configuration Release --no-restore

      # (Optional) run tests here if you want:
      # - name: "Test .NET"
      #   run: dotnet test MyMoviesApp.sln --no-build

      # 6) Publish .NET
      - name: "Publish .NET"
        run: dotnet publish MyMoviesApp.Api/MyMoviesApp.Api.csproj --configuration Release --no-build -o publish

      # 7) Copy Angular dist into wwwroot
      - name: "Copy Angular into wwwroot"
        run: |
          mkdir -p publish/wwwroot
          cp -r MyApp/dist/* publish/wwwroot/

      # 8) Deploy to Azure Web App
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "YourAzureWebAppName"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: "publish"
