- uses: actions/checkout@v2

# Setup Node to build Angular
- name: Set up Node
  uses: actions/setup-node@v3
  with:
    node-version: '16'  # or 18

- name: Install and build Angular
  run: |
    cd AngularProjectFolder
    npm install
    ng build --configuration production
    # Output goes to ../<YourDotNetProject>/wwwroot if angular.json is set that way

# Now build/publish .NET
- name: Set up .NET
  uses: actions/setup-dotnet@v2
  with:
    dotnet-version: '6.0.x'  # or 7.0 or 8.0

- name: dotnet publish
  run: |
    cd ../<YourDotNetProject>
    dotnet publish -c Release -o out

# Finally deploy to Azure
- name: Deploy to Azure WebApp
  uses: azure/webapps-deploy@v2
  with:
    app-name: '<YourAzureWebAppName>'
    publish-profile: ${{ secrets.<YourAzurePublishProfile> }}
    package: './out'
